force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager_Name__c</fullName>
    <defaultValue>&quot;Keshav Sharma&quot;</defaultValue>
    <label>Manager Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TeamController.cls
public class TeamController {
	
    @AuraEnabled(Cacheable=true)
    public static Team__c[] getAllTeams() {
        return [SELECT Id, Name, Description__c, Manager_Name__c, Rating__c FROM Team__c ORDER BY Id LIMIT 10];
    }
    
    @AuraEnabled(Cacheable=true)
    public static Team__c[] searchTeams(String searchTerm) {
        // Return all teams when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllTeams();
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [SELECT Id, Name, Description__c, Manager_Name__c, Rating__c FROM Team__c WHERE Name LIKE :searchTerm ORDER BY Id LIMIT 10];
    }
    
    @AuraEnabled(Cacheable=true)
    public static Team__c getTeamById(String teamId) {
        // Execute search query
        return [SELECT Id, Name, Description__c, Manager_Name__c, Rating__c FROM Team__c WHERE Id =:teamId];
    }

}