force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <defaultValue>&quot;Team_Member_Default.jpg&quot;</defaultValue>
    <label>Image Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Salesforce Apex</fullName>
            </value>
            <value>
                <fullName>Salesforce Lightning</fullName>
            </value>
            <value>
                <fullName>Reports and Dashboards</fullName>
            </value>
            <value>
                <fullName>Mulesoft API</fullName>
            </value>
            <value>
                <fullName>Test Automation</fullName>
            </value>
            <value>
                <fullName>UI/UX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeamMemberController.cls
public class TeamMemberController {

    @AuraEnabled(Cacheable=true)
    public static Team_Member__c[] getAllTeamMembers() {
        return [SELECT Id, Name FROM Team_Member__c ORDER BY Id LIMIT 10];
    }
    
    @AuraEnabled(Cacheable=true)
    public static Team_Member__c[] searchTeamMembers(String searchTerm) {
        // Return all team members when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllTeamMembers();
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [SELECT Id, Name, Skills__c, Employee_Id__c FROM Team_Member__c WHERE Name LIKE :searchTerm ORDER BY Id LIMIT 10];
    }
    
    @AuraEnabled(Cacheable=true)
    public static Team_Member__c[] getAllTeamMembersOfATeam(String teamId) {
        if(String.isNotBlank(teamId)){
            return [SELECT Id, Name FROM Team_Member__c WHERE Team__c =:teamId ORDER BY Id];
        }
        return new List<Team_Member__c>();
    }
    
    @AuraEnabled(Cacheable=true)
    public static Team_Member__c[] searchTeamMembersOfATeam(String searchTerm, String teamId) {
        // Return all team members when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllTeamMembersOfATeam(teamId);
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        if(String.isNotBlank(teamId)){
            return [SELECT Id, Name FROM Team_Member__c WHERE Name LIKE :searchTerm AND Team__c =:teamId ORDER BY Id LIMIT 10];
        }
        return new List<Team_Member__c>();
    }
    
    @AuraEnabled(Cacheable=true)
    public static Team_Member__c getTeamMemberById(String teamMemberId) {
        if(String.isNotBlank(teamMemberId)){
            List<Team_Member__c> listOfTMs = [SELECT Id, Name, Skills__c, Image_Name__c, Employee_Id__c FROM Team_Member__c WHERE Id =:teamMemberId LIMIT 1];
        	System.debug(listOfTMs);
        	return listOfTMs[0];
        }
  		return null;
    }
}